In [ ]:
## NUMPY BASICS
# [1,2,3,4,5] # vector/array
# [[1,2,3], 
# [4,5,6]] # matrix

In [2]:
import numpy as np

#without numpy:
temperatures = [36.6, 37.0, 37.5, 39.0]
total = 0
for temp in temperatures:
    total += temp
mean_temp = total / len(temperatures)
print("Mean temperature without numpy:", mean_temp)

#with numpy:
average = np.mean(temperatures)
print("Mean temperature with numpy:", average)


Mean temperature without numpy: 37.525
Mean temperature with numpy: 37.525


In [11]:
#1-D array

ar_1d = np.array([1,2,3,4,5])
print("1-D Array:", ar_1d)

#2-D array
ar_2d = np.array([[1,2,3],[4,5,6]])
print("2-D Array:")
print(ar_2d)

# Multidimensional array
ar_nd = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print("n-D Array:")
print(ar_nd)

## with default values
#zeros
zeros_array = np.zeros((2,3))# 2 rows, 3 columns (shape)
print("Zeros Array:")
print(zeros_array)
#ones
ones_array = np.ones((3,2))
print("Ones Array:")
print(ones_array)
#full
full_array = np.full((2,2), 7) # shape, fill_value
print("Full Array:")
print(full_array)


1-D Array: [1 2 3 4 5]
2-D Array:
[[1 2 3]
 [4 5 6]]
n-D Array:
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
Zeros Array:
[[0. 0. 0.]
 [0. 0. 0.]]
Ones Array:
[[1. 1.]
 [1. 1.]
 [1. 1.]]
Full Array:
[[7 7]
 [7 7]]


In [16]:
#Creating sequences of numbers in numpy

#arange()
arange_array = np.arange(0, 10, 2) # start, stop, step
print("Arange Array:")
print(arange_array)

#Creating identity matrix
#eye()
identity_matrix = np.eye(3, 3) # size
print("Identity Matrix:")
print(identity_matrix)



Arange Array:
[0 2 4 6 8]
Identity Matrix:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
#Properties and Calculations on Numpy Arrays

#shape
print("Shape of ar_2d:", ar_2d.shape) # rows, columns

#size
print("Size of ar_2d:", ar_2d.size) #no. of elements

#dtype
print("Data type of ar_2d:", ar_2d.dtype)

#ndim
print("Number of dimensions of ar_nd:", ar_nd.ndim)

# astype()
float_array = ar_1d.astype(float) # convert to float
print("Array converted to float:")
print(float_array)

# Mathematical operations
array_a = np.array([1,2,3])

print(array_a + 5) # add scalar
print(array_a * 2) # multiply by scalar
print(array_a - 1) # subtract scalar
print(array_a / 2) # divide by scalar
print(array_a ** 2) # square each element

# print(np.sqrt(array_a)) # square root of each element
# print(np.log(array_a)) # natural logarithm of each element
# print(np.exp(array_a)) # exponential of each element
# print(np.sin(array_a)) # sine of each element
# print(np.cos(array_a)) # cosine of each element
# print(np.tan(array_a)) # tangent of each element
# print(np.sum(array_a)) # sum of all elements
# print(np.mean(array_a)) # mean of all elements
# print(np.median(array_a)) # median of all elements
# print(np.std(array_a)) # standard deviation of all elements
# print(np.var(array_a)) # variance of all elements
# print(np.min(array_a)) # minimum element
# print(np.max(array_a)) # maximum element
# print(np.argmin(array_a)) # index of minimum element
# print(np.argmax(array_a)) # index of maximum element
# print(np.sort(array_a)) # sorted array
# print(np.unique(array_a)) # unique elements in the array
# print(np.concatenate((array_a, array_a))) # concatenate two arrays
# print(np.reshape(array_a, (3,1))) # reshape array to 3 rows, 1 column
# print(np.transpose(ar_2d)) # transpose of 2-D array
# print(np.dot(ar_2d, np.array([[1],[2],[3]]))) # matrix multiplication
# print(np.cross(np.array([1,0,0]), np.array([0,1,0]))) # cross product of two vectors
# print(np.linalg.inv(np.array([[1,2],[3,4]]))) # inverse of a matrix
# print(np.linalg.det(np.array([[1,2],[3,4]]))) # determinant of a matrix
# print(np.linalg.eig(np.array([[1,2],[2,1]]))) # eigenvalues and eigenvectors of a matrix
# print(np.linspace(0, 1, 5)) # generate 5 evenly spaced numbers between 0 and 1
# print(np.random.rand(3,2)) # generate a 3x2 array of random numbers between 0 and 1
# print(np.random.randint(0, 10, (2,3))) # generate a



Shape of ar_2d: (2, 3)
Size of ar_2d: 6
Data type of ar_2d: int64
Number of dimensions of ar_nd: 3
Array converted to float:
[1. 2. 3. 4. 5.]
[6 7 8]
[2 4 6]
[0 1 2]
[0.5 1.  1.5]
[1 4 9]
[1.         1.41421356 1.73205081]
[0.         0.69314718 1.09861229]
[ 2.71828183  7.3890561  20.08553692]


In [20]:

#aggregation functions
print("Sum of array_a:", np.sum(array_a)) # sum of all elements
print("Mean of array_a:", np.mean(array_a)) # mean of all elements
print("Min of array_a:", np.min(array_a)) # min of all elements
print("Mean of ar_2d along axis 0 (columns):", np.mean(ar_2d, axis=0)) # mean along columns
print("Mean of ar_2d along axis 1 (rows):", np.mean(ar_2d, axis=1)) # mean along rows
print("Standard Deviation of array_a:", np.std(array_a)) # standard deviation of all elements
print("Variance of array_a:", np.var(array_a)) # variance of all elements


Sum of array_a: 6
Mean of array_a: 2.0
Min of array_a: 1
Mean of ar_2d along axis 0 (columns): [2.5 3.5 4.5]
Mean of ar_2d along axis 1 (rows): [2. 5.]
Standard Deviation of array_a: 0.816496580927726
Variance of array_a: 0.6666666666666666


### Indexing and Slicing 
### Fancy indexing
### Boolean masking

In [9]:
# indexing
""" array[index] # for 1-D array
    array[row, column] # for 2-D array"""
import numpy as np

#1-D array indexing
ar_1dd = np.array([10, 20, 30, 40, 50])
print("Element at index 2 in ar_1d:", ar_1dd[2])  # 30

#2-D array indexing
ar_2dd = np.array([[10, 20, 30],
                    [40, 50, 60]])
print("Element at row 1, column 2 in ar_2d:", ar_2dd[-1, 2])  # 60

#Slicing [start:stop:step], stop is exclusive.
#1-D array slicing
print("Elements from index 1 to 3 in ar_1d:", ar_1dd[1:4])  # [20 30 40]

#2-D array slicing
print("Elements from row 0, columns 1 to 2 in ar_2d:", ar_2dd[0, 1:3])  # [20 30]

#Advanced Indexing
print(ar_1dd[1:4:2])  # select every second element from index 1 to 3
print(ar_1dd[::-1])  # reverse the array
print(ar_2dd[::2, ::2])  # select every second row and every second column

Element at index 2 in ar_1d: 30
Element at row 1, column 2 in ar_2d: 60
Elements from index 1 to 3 in ar_1d: [20 30 40]
Elements from row 0, columns 1 to 2 in ar_2d: [20 30]
[20 40]
[50 40 30 20 10]
[[10 30]]


In [10]:
# fancy indexing
indices = [0, 2, 4]
print("Fancy indexing on ar_1d:", ar_1dd[indices])  # [10 30 50]

# boolean masking (filtering data based on conditions)
mask = ar_1dd > 25
print("Boolean masking on ar_1d:", ar_1dd[mask])  # [30 40 50]

Fancy indexing on ar_1d: [10 30 50]
Boolean masking on ar_1d: [30 40 50]


### Reshaping & Manipulating Arrays!

In [ ]:
import numpy as np
# Changing the shape or dimensions of an array without changing its data
# It does not create a copy of the data, just a new view with a different shape
ar = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8]])
# Reshaping
reshaped_ar = ar.reshape((4, 2))  # new shape (4 rows, 2 columns)
print("Reshaped Array (4x2):")
print(reshaped_ar)

Reshaped Array (4x2):
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


### Flattening Array
### ravel(), flatten()

In [12]:
# multidimensional array to 1-D array
"""ravel() -> view
flatten() -> copy"""

import numpy as np
ar_nd = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
# Using ravel()
raveled_ar = ar_nd.ravel()
print("Raveled Array:")
print(raveled_ar)

# Using flatten()
flattened_ar = ar_nd.flatten()
print("Flattened Array:")
print(flattened_ar)

Raveled Array:
[1 2 3 4 5 6 7 8]
Flattened Array:
[1 2 3 4 5 6 7 8]


### Array Modification

In [ ]:
# add, remove, stack, split arrays
import numpy as np


# Adding arrays
ar1 = np.array([1, 2, 3])
ar2 = np.array([4, 5, 6])
ar_add = np.add(ar1, ar2)
print("Addition of arrays:")
print(ar_add)

""" np.insert(array, index, value, axis=None)
    axis = None for 1-D array 
    axis = 0 for rows in 2-D array
    axis = 1 for columns in 2-D array 
"""

# Inserting elements
ar_insert = np.insert(ar1, 1, 10)  # insert 10 at index 1
print("Array after insertion:")
print(ar_insert)

# inserting a new row in 2-D array
ar_2d = np.array([[1, 2, 3],
                   [4, 5, 6]])
ar_insert_2d = np.insert(ar_2d, 1, [10, 11, 12], axis=0)  # insert new row at index 1
print("2-D Array after row insertion:")
print(ar_insert_2d)
ar_insert_2d = np.insert(ar_2d, 1, [10, 11], axis=1)  # insert new column at index 1
print("2-D Array after column insertion:")
print(ar_insert_2d)

# Removing elements
ar_remove = np.delete(ar1, 1)  # remove element at index 1
print("Array after removal:")
print(ar_remove)

# Stacking arrays
ar_stack = np.vstack((ar2, ar1)) # vertical stack it stacks arrays row-wise and stacking means putting them on top of each other
print("Stacked arrays:")
print(ar_stack)

# Splitting arrays
""" np.arr.split() -> equally split
    np.arr.hsplit() -> horizontal split
    np.arr.vsplit() -> vertical split
"""
ar_split = np.split(ar1, 3)  # split into 3 parts
print("Split arrays:")
print(ar_split)

# appending elements
ar_append = np.append(ar1, [7, 8, 9], axis=0)
print("Array after appending elements:")
print(ar_append)

#concatenating arrays
ar_concat = np.concatenate((ar1, ar2), axis=0)
print("Array after concatenating:")
print(ar_concat)

# deleting elements, and rows/columns
ar_delete = np.delete(ar_2d, 0, axis=0)  # delete first row
print("2-D Array after deleting first row:")
print(ar_delete)

Addition of arrays:
[5 7 9]
Array after insertion:
[ 1 10  2  3]
2-D Array after row insertion:
[[ 1  2  3]
 [10 11 12]
 [ 4  5  6]]
2-D Array after column insertion:
[[ 1 10  2  3]
 [ 4 11  5  6]]
Array after removal:
[1 3]
Stacked arrays:
[[4 5 6]
 [1 2 3]]
Split arrays:
[array([1]), array([2]), array([3])]
Array after appending elements:
[1 2 3 7 8 9]
Array after concatenating:
[1 2 3 4 5 6]
2-D Array after deleting first row:
[[4 5 6]]


### Broadcasting and Vectorization

In [ ]:
prices = [100, 150, 200, 250, 300]
discount = 10  # 10% discount
final_prices = []

for price in prices:
    discounted_price = price - (price * discount / 100)
    final_prices.append(discounted_price)

print(final_prices)

# using broadcasting
import numpy as np
prices_array = np.array(prices)
final_prices_array = prices_array - (prices_array * discount / 100)
print(final_prices_array)


[90.0, 135.0, 180.0, 225.0, 270.0]
[ 90. 135. 180. 225. 270.]


## How numpy handles arrays of different dimensions

In [ ]:
## How numpy handles arrays of different dimensions
# Matching dimensions
ar1 = np.array([[1, 2, 3],
                 [4, 5, 6]])
ar2 = np.array([[10, 20, 30],
                 [40, 50, 60]])

ar_sum = ar1 + ar2  # no broadcasting, shapes are compatible
print("Sum of ar1 and ar2 with matching dimensions:")
print(ar_sum)

# Expanding single elements
ar3 = np.array([[100],
                 [200]])
ar_combined = ar1 + ar3  # broadcasting happens here
print("Sum of ar1 and ar3 with broadcasting:")
print(ar_combined)

# Incompatible shapes
ar4 = np.array([[1, 2],
                 [3, 4],
                 [5, 6]])
# This will raise an error due to incompatible shapes
# ar_invalid = ar1 + ar4

Sum of ar1 and ar2 with matching dimensions:
[[11 22 33]
 [44 55 66]]
Sum of ar1 and ar3 with broadcasting:
[[101 102 103]
 [204 205 206]]


In [10]:
# 1d to 2d

a = np.array([1, 2, 3])
b = np.array([[1, 2, 3],
                 [4, 5, 6]])
c = a + b  # broadcasting happens here
print("Sum of 1-D array a and 2-D array b with broadcasting:")  
print(c)

ab = np.array([1, 2, 3])
cd = np.array([1,2])
# This will raise an error due to incompatible shapes
# result = ab + cd

# solving incompatible shapes by reshaping
cd_reshaped = cd.reshape((2, 1))  # reshape cd to (2, 1)
print("Reshaped cd:")
print(cd_reshaped)
result = ab + cd_reshaped  # broadcasting happens here
print("Sum of ab and reshaped cd with broadcasting:")
print(result)

Sum of 1-D array a and 2-D array b with broadcasting:
[[2 4 6]
 [5 7 9]]
Reshaped cd:
[[1]
 [2]]
Sum of ab and reshaped cd with broadcasting:
[[2 3 4]
 [3 4 5]]


# vectorization

In [ ]:
# vectorization is the process of converting iterative operations
# into array operations to improve performance and efficiency.
import numpy as np
# Without vectorization
numbers = np.array([1, 2, 3, 4, 5])
squared = np.array([x**2 for x in numbers])
print("Squared numbers without vectorization:")
print(squared)

# With vectorization [much faster]
squared_vectorized = numbers ** 2
print("Squared numbers with vectorization:")
print(squared_vectorized)

Squared numbers without vectorization:
[ 1  4  9 16 25]
Squared numbers with vectorization:
[ 1  4  9 16 25]


## Handling missing values

In [ ]:
# Handling missing values using numpy's built-in functions
import numpy as np
# isnan(), isfinite(), isinf()
"""
np.isnan() -> detect missing values (NaN)
np.nan_to_num() -> replace NaN with specified value
np.isfinite() -> detect finite values (not NaN or Inf)
np.isinf() -> detect infinite values
"""

data = np.array([1.0, 2.0, np.nan, 4.0, np.inf, -np.inf])

cleaned_data = np.nan_to_num(data, nan=0.0, posinf=1e10, neginf=-1e10)
print("Cleaned Data:")
print(cleaned_data)

# Detecting missing values
nan_mask = np.isnan(data)
print("NaN mask:")
print(nan_mask)
# Replacing missing values with zero
data_no_nan = np.nan_to_num(data, nan=0.0)
print("Data after replacing NaN with 0:")
print(data_no_nan)
# Detecting finite values
finite_mask = np.isfinite(data)
print("Finite mask:")
print(finite_mask)
# Detecting infinite values
inf_mask = np.isinf(data)
print("Infinite mask:")
print(inf_mask)
# Replacing infinite values with large finite numbers
data_no_inf = np.where(np.isinf(data), np.sign(data) * 1e10, data)
print("Data after replacing Inf with large finite numbers:")
print(data_no_inf)


NaN mask:
[False False  True False False False]
Data after replacing NaN with 0:
[ 1.00000000e+000  2.00000000e+000  0.00000000e+000  4.00000000e+000
  1.79769313e+308 -1.79769313e+308]
Finite mask:
[ True  True False  True False False]
Infinite mask:
[False False False False  True  True]
Data after replacing Inf with large finite numbers:
[ 1.e+00  2.e+00     nan  4.e+00  1.e+10 -1.e+10]
